name: air-quality-daily

on:
  schedule:
    - cron: '0 8 */3 * *'
  workflow_dispatch:

jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
      - name: checkout repo content
        uses: actions/checkout@v5

      - name: install uv
        uses: astral-sh/setup-uv@v6

      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: install python project
        run: uv sync --all-extras

      - name: execute python workflows from bash script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          uv run python src/pipelines/feature_pipeline/feature-pipeline.py
          uv run python src/pipelines/inference_pipeline/inference-pipeline.py

      - name: github pages publish
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Air Quality Dashboard published"
          commit_options: '--no-verify --signoff'

          file_pattern: 'docs/air-quality/assets/img/* docs/_includes/*'

          repository: .

          status_options: '--untracked-files=no'

          skip_dirty_check: true

          skip_fetch: true

          skip_checkout: true

          push_options: '--force'
