name: air-quality-daily

on:
  workflow_dispatch:
    #schedule:
    #- cron: '11 6 * * *'

jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v6

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: install python project
        run: uv sync --all-extras --no-dev

      - name: execute python workflows from bash script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          cd notebooks/4-feat_eng
          jupyter nbconvert --to notebook --execute 2_air_quality_feature_pipeline.ipynb
          cd ../7-deploy
          jupyter nbconvert --to notebook --execute 4_air_quality_batch_inference.ipynb

      - name: github pages publish
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Air Quality Dashboard published"
          commit_options: '--no-verify --signoff'

          file_pattern: 'docs/air-quality/assets/img/* docs/_includes/*'

          repository: .

          status_options: '--untracked-files=no'

          skip_dirty_check: true

          skip_fetch: true

          skip_checkout: true

          push_options: '--force'
